arb-dir: lib/core/translations/
template-arb-file: app_en.arb
output-dir: lib/core/translations/generated/
output-localization-file: app_localizations.dart
output-class: AppLocalizations
preferred-supported-locales:
  - en
  - vi